var config = {

version: "2016.1.5",

modes: {
  "factory": "Erstinstallation (Neu gekaufter Router)",
  "sysupgrade": "Manuelles Update eines bestehenden Freifunk-Routers"
},

sites:{
  "domaene01" : {id:"domaene01",short:"ffmsd01",fwurl:"firmware.freifunk-muensterland.de/domaene01",name:"Münster Stadt",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene02" : {id:"domaene02",short:"ffmsd02",fwurl:"firmware.freifunk-muensterland.de/domaene02",name:"Kreis Coesfeld",
	  version:"1.0.4", version_base:"2016.1.2", on_map: false},
  "domaene03" : {id:"domaene03",short:"ffmsd03",fwurl:"firmware.freifunk-muensterland.de/domaene03",name:"Kreis Steinfurt West",
	  version:"1.0.4", version_base:"2016.1.2", on_map: false},
  "domaene04" : {id:"domaene04",short:"ffmsd04",fwurl:"firmware.freifunk-muensterland.de/domaene04",name:"Kreis Steinfurt Ost",
	  version:"1.0.4", version_base:"2016.1.2", on_map: false},
  "domaene05" : {id:"domaene05",short:"ffmsd05",fwurl:"firmware.freifunk-muensterland.de/domaene05",name:"Münster Süd",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene06" : {id:"domaene06",short:"ffmsd06",fwurl:"firmware.freifunk-muensterland.de/domaene06",name:"Westmünsterland",
	  version:"1.1.4", version_base:"2016.1.5", on_map: false},
  "domaene07" : {id:"domaene07",short:"ffmsd07",fwurl:"firmware.freifunk-muensterland.de/domaene07",name:"Telgte",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene08" : {id:"domaene08",short:"ffmsd08",fwurl:"firmware.freifunk-muensterland.de/domaene08",name:"Gescher",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene09" : {id:"domaene09",short:"ffmsd09",fwurl:"firmware.freifunk-muensterland.de/domaene09",name:"Stadtlohn",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene10" : {id:"domaene10",short:"ffmsd10",fwurl:"firmware.freifunk-muensterland.de/domaene10",name:"Testdomäne",
	  version:"1.1.9", version_base:"2016.1.5", on_map: false},
  "domaene11" : {id:"domaene11",short:"ffmsd11",fwurl:"firmware.freifunk-muensterland.de/domaene11",name:"Bocholt",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene12" : {id:"domaene12",short:"ffmsd12",fwurl:"firmware.freifunk-muensterland.de/domaene12",name:"Dülmen (ohne Rorup)",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene13" : {id:"domaene13",short:"ffmsd13",fwurl:"firmware.freifunk-muensterland.de/domaene13",name:"Rorup",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene14" : {id:"domaene14",short:"ffmsd14",fwurl:"firmware.freifunk-muensterland.de/domaene14",name:"Raesfeld",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene15" : {id:"domaene15",short:"ffmsd15",fwurl:"firmware.freifunk-muensterland.de/domaene15",name:"Heek",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene16" : {id:"domaene16",short:"ffmsd16",fwurl:"firmware.freifunk-muensterland.de/domaene16",name:"Münster Promenade",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true },
  "domaene17" : {id:"domaene17",short:"ffmsd17",fwurl:"firmware.freifunk-muensterland.de/domaene17",name:"Emsdetten",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true },
  "domaene18" : {id:"domaene18",short:"ffmsd18",fwurl:"firmware.freifunk-muensterland.de/domaene18",name:"Greven",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene19" : {id:"domaene19",short:"ffmsd19",fwurl:"firmware.freifunk-muensterland.de/domaene19",name:"Neuenkirchen",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene20" : {id:"domaene20",short:"ffmsd20",fwurl:"firmware.freifunk-muensterland.de/domaene20",name:"Ochtrup",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene21" : {id:"domaene21",short:"ffmsd21",fwurl:"firmware.freifunk-muensterland.de/domaene21",name:"Rheine",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene22" : {id:"domaene22",short:"ffmsd22",fwurl:"firmware.freifunk-muensterland.de/domaene22",name:"Steinfurt",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene23" : {id:"domaene23",short:"ffmsd23",fwurl:"firmware.freifunk-muensterland.de/domaene23",name:"Metelen",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene24" : {id:"domaene24",short:"ffmsd24",fwurl:"firmware.freifunk-muensterland.de/domaene24",name:"Wettringen",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene25" : {id:"domaene25",short:"ffmsd25",fwurl:"firmware.freifunk-muensterland.de/domaene25",name:"Steinfurt-Ost",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene26" : {id:"domaene26",short:"ffmsd26",fwurl:"firmware.freifunk-muensterland.de/domaene26",name:"Borken",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene27" : {id:"domaene27",short:"ffmsd27",fwurl:"firmware.freifunk-muensterland.de/domaene27",name:"Selm",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene28" : {id:"domaene28",short:"ffmsd28",fwurl:"firmware.freifunk-muensterland.de/domaene28",name:"Horstmar",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene29" : {id:"domaene29",short:"ffmsd29",fwurl:"firmware.freifunk-muensterland.de/domaene29",name:"Laer",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene30" : {id:"domaene30",short:"ffmsd30",fwurl:"firmware.freifunk-muensterland.de/domaene30",name:"Nordwalde",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene31" : {id:"domaene31",short:"ffmsd31",fwurl:"firmware.freifunk-muensterland.de/domaene31",name:"Altenberge",
	  version:"1.1.6", version_base:"2016.1.5", on_map: true},
  "domaene32" : {id:"domaene32",short:"ffmsd32",fwurl:"firmware.freifunk-muensterland.de/domaene32",name:"Ahlen",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene33" : {id:"domaene33",short:"ffmsd33",fwurl:"firmware.freifunk-muensterland.de/domaene33",name:"Beckum",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene34" : {id:"domaene34",short:"ffmsd34",fwurl:"firmware.freifunk-muensterland.de/domaene34",name:"Beelen",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene35" : {id:"domaene35",short:"ffmsd35",fwurl:"firmware.freifunk-muensterland.de/domaene35",name:"Drensteinfurt",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene36" : {id:"domaene36",short:"ffmsd36",fwurl:"firmware.freifunk-muensterland.de/domaene36",name:"Ennigerloh",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene37" : {id:"domaene37",short:"ffmsd37",fwurl:"firmware.freifunk-muensterland.de/domaene37",name:"Everswinkel",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene38" : {id:"domaene38",short:"ffmsd38",fwurl:"firmware.freifunk-muensterland.de/domaene38",name:"Oelde",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene39" : {id:"domaene39",short:"ffmsd39",fwurl:"firmware.freifunk-muensterland.de/domaene39",name:"Ostbevern",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene40" : {id:"domaene40",short:"ffmsd40",fwurl:"firmware.freifunk-muensterland.de/domaene40",name:"Sassenberg",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene41" : {id:"domaene41",short:"ffmsd41",fwurl:"firmware.freifunk-muensterland.de/domaene41",name:"Sendenhorst",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene42" : {id:"domaene42",short:"ffmsd42",fwurl:"firmware.freifunk-muensterland.de/domaene42",name:"Wadersloh",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene43" : {id:"domaene43",short:"ffmsd43",fwurl:"firmware.freifunk-muensterland.de/domaene43",name:"Warendorf",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene44" : {id:"domaene44",short:"ffmsd44",fwurl:"firmware.freifunk-muensterland.de/domaene44",name:"Ascheberg",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene45" : {id:"domaene45",short:"ffmsd45",fwurl:"firmware.freifunk-muensterland.de/domaene45",name:"Billerbeck",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene46" : {id:"domaene46",short:"ffmsd46",fwurl:"firmware.freifunk-muensterland.de/domaene46",name:"Coesfeld",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene47" : {id:"domaene47",short:"ffmsd47",fwurl:"firmware.freifunk-muensterland.de/domaene47",name:"Havixbeck",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene48" : {id:"domaene48",short:"ffmsd48",fwurl:"firmware.freifunk-muensterland.de/domaene48",name:"Lüdinghausen",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene49" : {id:"domaene49",short:"ffmsd49",fwurl:"firmware.freifunk-muensterland.de/domaene49",name:"Nordkirchen",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene50" : {id:"domaene50",short:"ffmsd50",fwurl:"firmware.freifunk-muensterland.de/domaene50",name:"Nottuln",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene51" : {id:"domaene51",short:"ffmsd51",fwurl:"firmware.freifunk-muensterland.de/domaene51",name:"Olfen",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene52" : {id:"domaene52",short:"ffmsd52",fwurl:"firmware.freifunk-muensterland.de/domaene52",name:"Rosendahl",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene53" : {id:"domaene53",short:"ffmsd53",fwurl:"firmware.freifunk-muensterland.de/domaene53",name:"Senden",
	  version:"1.1.5", version_base:"2016.1.5", on_map: true},
  "domaene54" : {id:"domaene54",short:"ffmsd54",fwurl:"firmware.freifunk-muensterland.de/domaene54",name:"Ahaus",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene55" : {id:"domaene55",short:"ffmsd55",fwurl:"firmware.freifunk-muensterland.de/domaene55",name:"Heiden",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene56" : {id:"domaene56",short:"ffmsd56",fwurl:"firmware.freifunk-muensterland.de/domaene56",name:"Isselburg",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene57" : {id:"domaene57",short:"ffmsd57",fwurl:"firmware.freifunk-muensterland.de/domaene57",name:"Legden",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene58" : {id:"domaene58",short:"ffmsd58",fwurl:"firmware.freifunk-muensterland.de/domaene58",name:"Reken",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene59" : {id:"domaene59",short:"ffmsd59",fwurl:"firmware.freifunk-muensterland.de/domaene59",name:"Rhede",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene60" : {id:"domaene60",short:"ffmsd60",fwurl:"firmware.freifunk-muensterland.de/domaene60",name:"Schöppingen",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene61" : {id:"domaene61",short:"ffmsd61",fwurl:"firmware.freifunk-muensterland.de/domaene61",name:"Südlohn",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene62" : {id:"domaene62",short:"ffmsd62",fwurl:"firmware.freifunk-muensterland.de/domaene62",name:"Velen",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene63" : {id:"domaene63",short:"ffmsd63",fwurl:"firmware.freifunk-muensterland.de/domaene63",name:"Vreden",
	  version:"1.1.9", version_base:"2016.1.5", on_map: true},
  "domaene64" : {id:"domaene64",short:"ffmsd64",fwurl:"firmware.freifunk-muensterland.de/domaene64",name:"Test",
	  version:"1.1.9", version_base:"2016.1.5", on_map: false},
  "domaene65" : {id:"domaene65",short:"ffmsd65",fwurl:"firmware.freifunk-muensterland.de/domaene65",name:"Ramsch",
	  version:"1.1.9", version_base:"2016.1.5", on_map: false},
  "ffeldomaene01" : {id:"ffeldomaene01",short:"ffel01",fwurl:"firmware.freifunk-emscherland.de/domaene01",name:"Recklinghausen/Herten (Freifunk-Emscherland)",
	  version:"0.0.5", version_base:"2016.1.5", on_map: true},
  "ffeldomaene02" : {id:"ffeldomaene02",short:"ffel02",fwurl:"firmware.freifunk-emscherland.de/domaene02",name:"Gladbeck/Bottrop (Freifunk-Emscherland)",
	  version:"0.0.5", version_base:"2016.1.5", on_map: true},
  "ffeldomaene03" : {id:"ffeldomaene03",short:"ffel03",fwurl:"firmware.freifunk-emscherland.de/domaene03",name:"Dorsten/Marl (Freifunk-Emscherland)",
	  version:"0.0.5", version_base:"2016.1.5", on_map: true},
  "ffeldomaene04" : {id:"ffeldomaene04",short:"ffel04",fwurl:"firmware.freifunk-emscherland.de/domaene04",name:"Haltern am See/Raesfeld (Freifunk-Emscherland)",
	  version:"0.0.5", version_base:"2016.1.5", on_map: true}
},

manufacturers: {
  "0tp-link": {id: "tp-link", name: "TP-Link"},
  "1ubiquiti": {id: "ubiquiti", name: "Ubiquiti"},
  "2buffalo": {id: "buffalo", name: "Buffalo"},
  "3d-link": {id: "d-link", name: "D-Link"},
  "4gl-inet": {id: "gl-inet", name: "GL-Inet"},
  "5linksys": {id: "linksys", name: "Linksys"},
  "6netgear": {id: "netgear", name: "Netgear"},
  "7alfa": {id: "alfa", name: "ALFA-Network"},
  "88devices": {id: "8devices", name: "8devices"},
  "9meraki": {id: "meraki", name: "Meraki"},
  "10openmesh": {id: "openmesh", name: "OpenMesh"},
  "11onion": {id: "onion", name: "Onion"},
  "12wd-ny-net": {id: "wd-ny-net", name: "WD My Net"},
  "13x86":{id:"x86",name:"x86"}
},

routers: {
 //only works for sysupgrade "8devices-carambola2-board": { id: "8devices-carambola2-board", name: "carambola2-Board", manufacturer: "8devices" },
 "alfa-ap121": { id: "alfa-ap121", name: "AP121", manufacturer: "ALFA-Network" },
 "alfa-ap121u": { id: "alfa-ap121u", name: "AP121U", manufacturer: "ALFA-Network" },
 "alfa-hornet-ub": { id: "alfa-hornet-ub", name: "Hornet UB", manufacturer: "ALFA-Network" },
 //only works for sysupgrade "buffalo-wzr-hp-ag300h-wzr-600dhp": { id: "buffalo-wzr-hp-ag300h-wzr-600dhp", name: "WZR-600DHP", manufacturer: "Buffalo" },
 "buffalo-wzr-hp-ag300h": { id: "buffalo-wzr-hp-ag300h", name: "WZR-HG-AG300H", manufacturer: "Buffalo" }, // only works for factory
 "buffalo-wzr-600dhp": { id: "buffalo-wzr-600dhp", name: "WZR-600DHP", manufacturer: "Buffalo" }, // only works for factory
 "buffalo-wzr-hp-g450h": { id: "buffalo-wzr-hp-g450h", name: "WZR-HP-G450H", manufacturer: "Buffalo" },
 "buffalo-wzr-hp-g300nh": { id: "buffalo-wzr-hp-g300nh", name: "WZR-HP-G300NH ", manufacturer: "Buffalo" },
 "d-link-dir-505-rev-a1": { id: "d-link-dir-505-rev-a1", name: "DIR-505 (A1)", manufacturer: "D-Link" },
 "d-link-dir-615-rev-c1": { id: "d-link-dir-615-rev-c1", name: "615", manufacturer: "D-Link" },
 "d-link-dir-825-rev-b1": { id: "d-link-dir-825-rev-b1", name: "825", manufacturer: "D-Link" },
 "gl-inet-6408a-v1": { id: "gl-inet-6408a-v1", name: "6408A", manufacturer: "GL-Inet" },
 "gl-inet-6416a-v1": { id: "gl-inet-6416a-v1", name: "6416A", manufacturer: "GL-Inet" },
 "linksys-wrt160nl": { id: "linksys-wrt160nl", name: "WRT160NL", manufacturer: "Linksys" },
 //only works for sysupgrade "meraki-mr12": { id: "meraki-mr12", name: "MR12", manufacturer: "Meraki" },
 //only works for sysupgrade "meraki-mr16": { id: "meraki-mr16", name: "MR16", manufacturer: "Meraki" },
 //only works for sysupgrade "meraki-mr62": { id: "meraki-mr62", name: "MR62", manufacturer: "Meraki" },
 //only works for sysupgrade "meraki-mr66": { id: "meraki-mr66", name: "MR66", manufacturer: "Meraki" }, 
 "netgear-wndr3700": { id: "netgear-wndr3700", name: "WNDR3700 Ver:1", manufacturer: "Netgear", extension :"img", extensionupgrade :"bin" },
 "netgear-wndr3700v2": { id: "netgear-wndr3700v2", name: "WNDR3700 Ver:2", manufacturer: "Netgear", extension :"img", extensionupgrade :"bin" },
 "netgear-wndr3700v4": { id: "netgear-wndr3700v4", name: "WNDR3700 Ver:4", manufacturer: "Netgear", extension :"img", extensionupgrade :"bin" },
 "netgear-wndr3800": { id: "netgear-wndr3800", name: "WNDR3800 Ver:1", manufacturer: "Netgear", extension :"img", extensionupgrade :"bin" },
 "netgear-wndr4300": { id: "netgear-wndr4300", name: "WNDR4300 Ver:1", manufacturer: "Netgear", extension :"img", extensionupgrade :"bin" },
 "netgear-wndrmacv2": { id: "netgear-wndrmacv2", name: "WNDRMAC Ver:2", manufacturer: "Netgear", extension :"img", extensionupgrade :"bin" },
 "onion-omega": { id: "onion-omega", name: "Omega", manufacturer: "Onion" },
 "openmesh-mr600": { id: "openmesh-mr600", name: "MR600 Ver:1", manufacturer: "OpenMesh" },
 "openmesh-mr600v2": { id: "openmesh-mr600v2", name: "MR600 Ver:2", manufacturer: "OpenMesh" },
 "openmesh-mr900": { id: "openmesh-mr900", name: "MR900 Ver:1", manufacturer: "OpenMesh" },
 "openmesh-mr900v2": { id: "openmesh-mr900v2", name: "MR900 Ver:2", manufacturer: "OpenMesh" },
 "openmesh-om2p-hs": { id: "openmesh-om2p-hs", name: "OM2P-HS Ver:1", manufacturer: "OpenMesh" },
 "openmesh-om2p-hsv2": { id: "openmesh-om2p-hsv2", name: "OM2P-HS Ver:2", manufacturer: "OpenMesh" },
 "openmesh-om2p-lc": { id: "openmesh-om2p-lc", name: "OM2P-LC Ver:1", manufacturer: "OpenMesh" },
 "openmesh-om2p": { id: "openmesh-om2p", name: "OM2P Ver:1", manufacturer: "OpenMesh" },
 "openmesh-om2pv2": { id: "openmesh-om2pv2", name: "OM2P Ver:2", manufacturer: "OpenMesh" },
 "openmesh-om5p-an": { id: "openmesh-om5p-an", name: "OM5P-AN Ver:1", manufacturer: "OpenMesh" },
 "openmesh-om5p": { id: "openmesh-om5p", name: "OM5P Ver:1", manufacturer: "OpenMesh" },
 "tp-link-cpe210-v1.0": { id: "tp-link-cpe210-v1.0", name: "CPE210 Ver:1", manufacturer: "TP-Link" },
 "tp-link-cpe210-v1.1": { id: "tp-link-cpe210-v1.1", name: "CPE210 Ver:1.1", manufacturer: "TP-Link" },
 "tp-link-cpe220-v1.0": { id: "tp-link-cpe220-v1.0", name: "CPE220 Ver:1", manufacturer: "TP-Link" },
 "tp-link-cpe220-v1.1": { id: "tp-link-cpe220-v1.1", name: "CPE220 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-mr13u-v1": { id: "tp-link-tl-mr13u-v1", name: "TL-MR13U Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-mr3020-v1": { id: "tp-link-tl-mr3020-v1", name: "TL-MR3020 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-mr3040-v1": { id: "tp-link-tl-mr3040-v1", name: "TL-MR3040 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-mr3040-v2": { id: "tp-link-tl-mr3040-v2", name: "TL-MR3040 Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-mr3220-v1": { id: "tp-link-tl-mr3220-v1", name: "TL-MR3220 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-mr3220-v2": { id: "tp-link-tl-mr3220-v2", name: "TL-MR3220 Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-mr3420-v1": { id: "tp-link-tl-mr3420-v1", name: "TL-MR3420 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-mr3420-v2": { id: "tp-link-tl-mr3420-v2", name: "TL-MR3420 Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wa701n-nd-v1": { id: "tp-link-tl-wa701n-nd-v1", name: "TL-WA701N/ND", manufacturer: "TP-Link" },
 "tp-link-tl-wa750re-v1": { id: "tp-link-tl-wa750re-v1", name: "TL-WA750RE Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wa7510n-v1": { id: "tp-link-tl-wa7510n-v1", name: "TL-WA7510N Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wa801n-nd-v1": { id: "tp-link-tl-wa801n-nd-v1", name: "TL-WA801N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wa801n-nd-v2": { id: "tp-link-tl-wa801n-nd-v2", name: "TL-WA801N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wa830re-v1": { id: "tp-link-tl-wa830re-v1", name: "TL-WA830Re Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wa850re-v1": { id: "tp-link-tl-wa850re-v1", name: "TL-WA850RE Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wa860re-v1": { id: "tp-link-tl-wa860re-v1", name: "TL-WA860RE Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wa901n-nd-v2": { id: "tp-link-tl-wa901n-nd-v2", name: "TL-WA901N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wa901n-nd-v3": { id: "tp-link-tl-wa901n-nd-v3", name: "TL-WA901N/ND Ver:3", manufacturer: "TP-Link" },
 "tp-link-tl-wdr3500-v1": { id: "tp-link-tl-wdr3500-v1", name: "TL-WDR3500 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wdr3600-v1": { id: "tp-link-tl-wdr3600-v1", name: "TL-WDR3600 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wdr4300-v1": { id: "tp-link-tl-wdr4300-v1", name: "TL-WDR4300 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wdr4900-v1": { id: "tp-link-tl-wdr4900-v1", name: "TL-WDR4900 Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr703n-v1": { id: "tp-link-tl-wr703n-v1", name: "TL-WR703N Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr710n-v1": { id: "tp-link-tl-wr710n-v1", name: "TL-WR710N Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr710n-v2": { id: "tp-link-tl-wr710n-v2", name: "TL-WR710N v2", manufacturer: "TP-Link" },
 "tp-link-tl-wr740n-nd-v1": { id: "tp-link-tl-wr740n-nd-v1", name: "TL-WR740N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr740n-nd-v3": { id: "tp-link-tl-wr740n-nd-v3", name: "TL-WR740N/ND Ver:3", manufacturer: "TP-Link" },
 "tp-link-tl-wr740n-nd-v4": { id: "tp-link-tl-wr740n-nd-v4", name: "TL-WR740N/ND Ver:4", manufacturer: "TP-Link" },
 "tp-link-tl-wr741n-nd-v1": { id: "tp-link-tl-wr741n-nd-v1", name: "TL-WR741N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr741n-nd-v2": { id: "tp-link-tl-wr741n-nd-v2", name: "TL-WR741N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wr741n-nd-v4": { id: "tp-link-tl-wr741n-nd-v4", name: "TL-WR741N/ND Ver:4", manufacturer: "TP-Link" },
 "tp-link-tl-wr743n-nd-v1": { id: "tp-link-tl-wr743n-nd-v1", name: "TL-WR743N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr743n-nd-v2": { id: "tp-link-tl-wr743n-nd-v2", name: "TL-WR743N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wr841n-nd-v3": { id: "tp-link-tl-wr841n-nd-v3", name: "TL-WR841N/ND Ver:3", manufacturer: "TP-Link" },
 "tp-link-tl-wr841n-nd-v5": { id: "tp-link-tl-wr841n-nd-v5", name: "TL-WR841N/ND Ver:5", manufacturer: "TP-Link" },
 "tp-link-tl-wr841n-nd-v7": { id: "tp-link-tl-wr841n-nd-v7", name: "TL-WR841N/ND Ver:7", manufacturer: "TP-Link" },
 "tp-link-tl-wr841n-nd-v8": { id: "tp-link-tl-wr841n-nd-v8", name: "TL-WR841N/ND Ver:8", manufacturer: "TP-Link" },
 "tp-link-tl-wr841n-nd-v9": { id: "tp-link-tl-wr841n-nd-v9", name: "TL-WR841N/ND Ver:9", manufacturer: "TP-Link" },
 "tp-link-tl-wr841n-nd-v10": { id: "tp-link-tl-wr841n-nd-v10", name: "TL-WR841N/ND Ver:10", manufacturer: "TP-Link" },
 "tp-link-tl-wr841n-nd-v11": { id: "tp-link-tl-wr841n-nd-v11", name: "TL-WR841N/ND Ver:11", manufacturer: "TP-Link" },
 "tp-link-tl-wr842n-nd-v1": { id: "tp-link-tl-wr842n-nd-v1", name: "TL-WR842N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr842n-nd-v2": { id: "tp-link-tl-wr842n-nd-v2", name: "TL-WR842N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wr843n-nd-v1": { id: "tp-link-tl-wr843n-nd-v1", name: "TL-WR843N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wa901n-nd-v1": { id: "tp-link-tl-wa901n-nd-v1", name: "TL-WA901N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr940n-nd-v1": { id: "tp-link-tl-wr940n-nd-v1", name: "TL-WR940N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link tl-wr940n-nd-v2": { id: "tp-link-tl-wr940n-nd-v2", name: "TL-WR940N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wr940n-nd-v3": { id: "tp-link-tl-wr940n-nd-v3", name: "TL-WR940N/ND Ver:3", manufacturer: "TP-Link" },
 "tp-link-tl-wr941n-nd-v2": { id: "tp-link-tl-wr941n-nd-v2", name: "TL-WR941N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wr941n-nd-v3": { id: "tp-link-tl-wr941n-nd-v3", name: "TL-WR941N/ND Ver:3", manufacturer: "TP-Link" },
 "tp-link-tl-wr941n-nd-v4": { id: "tp-link-tl-wr941n-nd-v4", name: "TL-WR941N/ND Ver:4", manufacturer: "TP-Link" },
 "tp-link-tl-wr941n-nd-v5": { id: "tp-link-tl-wr941n-nd-v5", name: "TL-WR941N/ND Ver:5", manufacturer: "TP-Link" },
 "tp-link-tl-wr941n-nd-v6": { id: "tp-link-tl-wr941n-nd-v6", name: "TL-WR941N/ND Ver:6", manufacturer: "TP-Link" },
 "tp-link-tl-wr1043n-nd-v1": { id: "tp-link-tl-wr1043n-nd-v1", name: "TL-WR1043N/ND Ver:1", manufacturer: "TP-Link" },
 "tp-link-tl-wr1043n-nd-v2": { id: "tp-link-tl-wr1043n-nd-v2", name: "TL-WR1043N/ND Ver:2", manufacturer: "TP-Link" },
 "tp-link-tl-wr1043n-nd-v3": { id: "tp-link-tl-wr1043n-nd-v3", name: "TL-WR1043N-ND Ver:3", manufacturer: "TP-Link" },
 "tp-link-tl-wr2543n-nd-v1": { id: "tp-link-tl-wr2543n-nd-v1", name: "TL-WR2543N/ND Ver:1", manufacturer: "TP-Link" },
 "ubiquiti-bullet-m":        { id: "ubiquiti-bullet-m", name: "Bullet M", manufacturer: "Ubiquiti" },
 "ubiquiti-loco-m-xw":      { id: "ubiquiti-loco-m-xw", name: "Loco M XW", manufacturer: "Ubiquiti" },
 "ubiquiti-rocket-m-xw":{id:"ubiquiti-rocket-m-xw",name:"Rocket M XW",manufacturer:"Ubiquiti"}, 
 "ubiquiti-rocket-m":{id:"ubiquiti-rocket-m",name:"Rocket M",manufacturer:"Ubiquiti"},
 "ubiquiti-nanostation-m-xw": { id: "ubiquiti-nanostation-m-xw", name: "Nanostation M XW", manufacturer: "Ubiquiti" },
 "ubiquiti-nanostation-m": { id: "ubiquiti-nanostation-m", name: "Nanostation M", manufacturer: "Ubiquiti" },
 "ubiquiti-picostation-m":{id:"ubiquiti-picostation-m",name:"Picostation M",manufacturer:"Ubiquiti"},
 "ubiquiti-unifi": { id: "ubiquiti-unifi", name: "UniFi", manufacturer: "Ubiquiti" },
 "ubiquiti-unifi-ap-pro": { id: "ubiquiti-unifi-ap-pro", name: "UniFi AP Pro", manufacturer: "Ubiquiti" },
 "ubiquiti-unifiap-outdoor": { id: "ubiquiti-unifiap-outdoor", name: "UniFi AP Outdoor", manufacturer: "Ubiquiti" },
 "ubiquiti-unifiap-outdoor+": { id: "ubiquiti-unifiap-outdoor+", name: "Outdoor+", manufacturer: "Ubiquiti" },
 "ubiquiti-airgateway": { id: "ubiquiti-airgateway", name: "airGateway ", manufacturer: "Ubiquiti" },
 "ubiquiti-airrouter": { id: "ubiquiti-airrouter", name: "airRouter ", manufacturer: "Ubiquiti" },
 "wd-my-net-n600": { id: "wd-my-net-n600", name: "N600", manufacturer: "WD My Net" },
 "wd-my-net-n750": { id: "wd-my-net-n750", name: "N750", manufacturer: "WD My Net" },
 "x86-generic":{id:"x86-generic.img.gz",name:"generic", extension :"img.gz" },
 "x86-kvm":{id:"x86-kvm",name:"kvm",manufacturer:"x86", extension :"img.gz" },
 "x86-virtualbox":{id:"x86-virtualbox",name:"virtualbox",manufacturer:"x86", extension :"vdi" }, // only available for factory
 "x86-vmware":{id:"x86-vmware",name:"vmware",manufacturer:"x86", extension :"vmdk" }, // only abailable for factory
},

name: "Münsterland",


url: "http://{{parse(downloadableSite).fwurl}}/versions/v{{parse(downloadableSite).version}}/{{selectedMode}}/gluon-{{parse(downloadableSite).short}}-v" +
"{{parse(downloadableSite).version_base}}+{{parse(downloadableSite).version}}-{{parse(selectedRouter).id}}{{selectedMode=='sysupgrade'?'-sysupgrade':''}}"
}

